# Generated by Django 3.1.3 on 2020-11-22 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_categories',
            old_name='caterogy',
            new_name='category',
        ),
    ]
