# Generated by Django 3.1.3 on 2020-11-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201122_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='reference_image',
            field=models.ImageField(blank=True, default='default.png', upload_to='listingimages/'),
        ),
    ]
