# Generated by Django 3.1.3 on 2020-11-22 21:29

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201122_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='reference_image',
            field=models.ImageField(default='listingimages/default.png', height_field=100, upload_to=auctions.models.user_directory_path, width_field=100),
        ),
    ]
