# Generated by Django 3.1.3 on 2020-11-22 21:53

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201122_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='reference_image',
            field=models.ImageField(default='auctions/templates/auctions/listingimages/default.png', upload_to=auctions.models.user_directory_path),
        ),
    ]
