# Generated by Django 3.1.3 on 2020-12-10 22:42

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20201122_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='current_bid',
            field=models.IntegerField(default=100, validators=[auctions.models.valid_bid]),
            preserve_default=False,
        ),
    ]
