# Generated by Django 3.1.3 on 2020-12-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20201214_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='reference_image',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
