# Generated by Django 3.1.3 on 2020-12-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20201215_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='reference_image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='auctions/listingimages/'),
        ),
    ]
